[package]
name = "fedimint-client-uniffi"
version = "0.11.1"
edition = "2021"
license = "MIT"
authors = ["The Fedimint Developers"]
description = "fedimint client for uniffi"
readme = "README.md"
repository = "https://github.com/fedimint/fedimint"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]
name = "fedimint_client_uniffi"
path = "src/lib.rs"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[features]
default = []
uniffi = []
tokio-multi-thread = ["tokio/rt-multi-thread"]

[dependencies]
anyhow = "1.0.98"
async-stream = "0.3"
fedimint-bip39 = { path = "../../../fedimint/fedimint-bip39" }
fedimint-client = { path = "../../../fedimint/fedimint-client", features = ["uniffi"] }
fedimint-connectors = { path = "../../../fedimint/fedimint-connectors" }
fedimint-core = { path = "../../../fedimint/fedimint-core", features = ["uniffi"] }
fedimint-derive-secret = { path = "../../../fedimint/crypto/derive-secret" }
fedimint-ln-client = { path = "../../../fedimint/modules/fedimint-ln-client", features = ["uniffi"] }
fedimint-meta-client = { path = "../../../fedimint/modules/fedimint-meta-client", features = ["uniffi"] }
fedimint-mint-client = { path = "../../../fedimint/modules/fedimint-mint-client", features = ["uniffi"] }
fedimint-wallet-client = { path = "../../../fedimint/modules/fedimint-wallet-client", features = ["uniffi"] }
futures = "0.3"
rand = "0.8"
thiserror = "2.0.12"
log = "0.4"
tracing = "0.1"
uniffi = { version = "0.32.0", features = ["cli", "tokio"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fedimint-rocksdb = { path = "../../../fedimint/fedimint-rocksdb" }
socket2 = { version = "0.5.7", features = ["all"] }
tokio = { version = "1.48.0", default-features = false, features = ["sync", "rt-multi-thread", "fs"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
fedimint-cursed-redb = { path = "../../../fedimint/fedimint-cursed-redb" }
tokio = { version = "1.48.0", default-features = false, features = ["sync", "rt", "macros", "time", "io-util"] }

[target.'cfg(target_os = "android")'.dependencies] 
android_logger = "0.14"

[build-dependencies]
cc = "1"
fedimint-build = { path = "../../../fedimint/fedimint-build" }
uniffi = { version = "0.32.0", features = ["build"] }

[profile.release]
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = "abort"     # Abort on panic
strip = "debuginfo" # Partially strip symbols from binary